import 'package:flutter/material.dart';

class ExampleTextTheme {
  late final TextStyle titlesTitle01;
  late final TextStyle titlesTitle02;
  late final TextStyle titlesTitle03;
  late final TextStyle titlesTitle04;
  late final TextStyle textMediumDefault;
  late final TextStyle textMediumDefaultUppercase;
  late final TextStyle textMediumDefaultUnderline;
  late final TextStyle textMediumStrong;
  late final TextStyle textMediumStrongUppercase;
  late final TextStyle textMediumStrongUnderline;
  late final TextStyle textSmallDefault;
  late final TextStyle textSmallDefaultUppercase;
  late final TextStyle textSmallDefaultUnderline;
  late final TextStyle textSmallStrong;
  late final TextStyle textSmallStrongUppercase;
  late final TextStyle textSmallStrongUnderline;
  late final TextStyle textXsmallDefault;
  late final TextStyle textXsmallDefaultUppercase;
  late final TextStyle textXsmallDefaultUnderline;
  late final TextStyle textXsmallStrong;
  late final TextStyle textXsmallStrongUppercase;
  late final TextStyle textXsmallStrongUnderline;
  late final TextStyle textTinyDefault;
  late final TextStyle textTinyDefaultUppercase;
  late final TextStyle textTinyDefaultUnderline;
  late final TextStyle textTinyStrong;
  late final TextStyle textTinyStrongUppercase;
  late final TextStyle textTinyStrongUnderline;

  ExampleTextTheme({
    TextStyle? allOverrides,
    TextStyle? titlesTitle01Overrides,
    TextStyle? titlesTitle02Overrides,
    TextStyle? titlesTitle03Overrides,
    TextStyle? titlesTitle04Overrides,
    TextStyle? textMediumDefaultOverrides,
    TextStyle? textMediumDefaultUppercaseOverrides,
    TextStyle? textMediumDefaultUnderlineOverrides,
    TextStyle? textMediumStrongOverrides,
    TextStyle? textMediumStrongUppercaseOverrides,
    TextStyle? textMediumStrongUnderlineOverrides,
    TextStyle? textSmallDefaultOverrides,
    TextStyle? textSmallDefaultUppercaseOverrides,
    TextStyle? textSmallDefaultUnderlineOverrides,
    TextStyle? textSmallStrongOverrides,
    TextStyle? textSmallStrongUppercaseOverrides,
    TextStyle? textSmallStrongUnderlineOverrides,
    TextStyle? textXsmallDefaultOverrides,
    TextStyle? textXsmallDefaultUppercaseOverrides,
    TextStyle? textXsmallDefaultUnderlineOverrides,
    TextStyle? textXsmallStrongOverrides,
    TextStyle? textXsmallStrongUppercaseOverrides,
    TextStyle? textXsmallStrongUnderlineOverrides,
    TextStyle? textTinyDefaultOverrides,
    TextStyle? textTinyDefaultUppercaseOverrides,
    TextStyle? textTinyDefaultUnderlineOverrides,
    TextStyle? textTinyStrongOverrides,
    TextStyle? textTinyStrongUppercaseOverrides,
    TextStyle? textTinyStrongUnderlineOverrides,
  }) {
    titlesTitle01 = TextStyle(
      inherit: titlesTitle01Overrides?.inherit ?? allOverrides?.inherit ?? true,
      color: titlesTitle01Overrides?.color ?? allOverrides?.color,
      backgroundColor: titlesTitle01Overrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: titlesTitle01Overrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.titles}",
      fontSize: titlesTitle01Overrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: titlesTitle01Overrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: titlesTitle01Overrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: titlesTitle01Overrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: titlesTitle01Overrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: titlesTitle01Overrides?.textBaseline ?? allOverrides?.textBaseline,
      height: titlesTitle01Overrides?.height ?? allOverrides?.height,
      decoration: titlesTitle01Overrides?.decoration ?? allOverrides?.decoration,
      decorationColor: titlesTitle01Overrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: titlesTitle01Overrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: titlesTitle01Overrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: titlesTitle01Overrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: titlesTitle01Overrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: titlesTitle01Overrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: titlesTitle01Overrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: titlesTitle01Overrides?.overflow ?? allOverrides?.overflow,
    );
    titlesTitle02 = TextStyle(
      inherit: titlesTitle02Overrides?.inherit ?? allOverrides?.inherit ?? true,
      color: titlesTitle02Overrides?.color ?? allOverrides?.color,
      backgroundColor: titlesTitle02Overrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: titlesTitle02Overrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.titles}",
      fontSize: titlesTitle02Overrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: titlesTitle02Overrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: titlesTitle02Overrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: titlesTitle02Overrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: titlesTitle02Overrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: titlesTitle02Overrides?.textBaseline ?? allOverrides?.textBaseline,
      height: titlesTitle02Overrides?.height ?? allOverrides?.height,
      decoration: titlesTitle02Overrides?.decoration ?? allOverrides?.decoration,
      decorationColor: titlesTitle02Overrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: titlesTitle02Overrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: titlesTitle02Overrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: titlesTitle02Overrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: titlesTitle02Overrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: titlesTitle02Overrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: titlesTitle02Overrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: titlesTitle02Overrides?.overflow ?? allOverrides?.overflow,
    );
    titlesTitle03 = TextStyle(
      inherit: titlesTitle03Overrides?.inherit ?? allOverrides?.inherit ?? true,
      color: titlesTitle03Overrides?.color ?? allOverrides?.color,
      backgroundColor: titlesTitle03Overrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: titlesTitle03Overrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.titles}",
      fontSize: titlesTitle03Overrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: titlesTitle03Overrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: titlesTitle03Overrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: titlesTitle03Overrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: titlesTitle03Overrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: titlesTitle03Overrides?.textBaseline ?? allOverrides?.textBaseline,
      height: titlesTitle03Overrides?.height ?? allOverrides?.height,
      decoration: titlesTitle03Overrides?.decoration ?? allOverrides?.decoration,
      decorationColor: titlesTitle03Overrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: titlesTitle03Overrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: titlesTitle03Overrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: titlesTitle03Overrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: titlesTitle03Overrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: titlesTitle03Overrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: titlesTitle03Overrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: titlesTitle03Overrides?.overflow ?? allOverrides?.overflow,
    );
    titlesTitle04 = TextStyle(
      inherit: titlesTitle04Overrides?.inherit ?? allOverrides?.inherit ?? true,
      color: titlesTitle04Overrides?.color ?? allOverrides?.color,
      backgroundColor: titlesTitle04Overrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: titlesTitle04Overrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.titles}",
      fontSize: titlesTitle04Overrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: titlesTitle04Overrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: titlesTitle04Overrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: titlesTitle04Overrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: titlesTitle04Overrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: titlesTitle04Overrides?.textBaseline ?? allOverrides?.textBaseline,
      height: titlesTitle04Overrides?.height ?? allOverrides?.height,
      decoration: titlesTitle04Overrides?.decoration ?? allOverrides?.decoration,
      decorationColor: titlesTitle04Overrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: titlesTitle04Overrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: titlesTitle04Overrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: titlesTitle04Overrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: titlesTitle04Overrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: titlesTitle04Overrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: titlesTitle04Overrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: titlesTitle04Overrides?.overflow ?? allOverrides?.overflow,
    );
    textMediumDefault = TextStyle(
      inherit: textMediumDefaultOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textMediumDefaultOverrides?.color ?? allOverrides?.color,
      backgroundColor: textMediumDefaultOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textMediumDefaultOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textMediumDefaultOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textMediumDefaultOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textMediumDefaultOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textMediumDefaultOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textMediumDefaultOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textMediumDefaultOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textMediumDefaultOverrides?.height ?? allOverrides?.height,
      decoration: textMediumDefaultOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textMediumDefaultOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textMediumDefaultOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textMediumDefaultOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textMediumDefaultOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textMediumDefaultOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textMediumDefaultOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textMediumDefaultOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textMediumDefaultOverrides?.overflow ?? allOverrides?.overflow,
    );
    textMediumDefaultUppercase = TextStyle(
      inherit: textMediumDefaultUppercaseOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textMediumDefaultUppercaseOverrides?.color ?? allOverrides?.color,
      backgroundColor: textMediumDefaultUppercaseOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textMediumDefaultUppercaseOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textMediumDefaultUppercaseOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textMediumDefaultUppercaseOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textMediumDefaultUppercaseOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textMediumDefaultUppercaseOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textMediumDefaultUppercaseOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textMediumDefaultUppercaseOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textMediumDefaultUppercaseOverrides?.height ?? allOverrides?.height,
      decoration: textMediumDefaultUppercaseOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textMediumDefaultUppercaseOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textMediumDefaultUppercaseOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textMediumDefaultUppercaseOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textMediumDefaultUppercaseOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textMediumDefaultUppercaseOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textMediumDefaultUppercaseOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textMediumDefaultUppercaseOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textMediumDefaultUppercaseOverrides?.overflow ?? allOverrides?.overflow,
    );
    textMediumDefaultUnderline = TextStyle(
      inherit: textMediumDefaultUnderlineOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textMediumDefaultUnderlineOverrides?.color ?? allOverrides?.color,
      backgroundColor: textMediumDefaultUnderlineOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textMediumDefaultUnderlineOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textMediumDefaultUnderlineOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textMediumDefaultUnderlineOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textMediumDefaultUnderlineOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textMediumDefaultUnderlineOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textMediumDefaultUnderlineOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textMediumDefaultUnderlineOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textMediumDefaultUnderlineOverrides?.height ?? allOverrides?.height,
      decoration: textMediumDefaultUnderlineOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textMediumDefaultUnderlineOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textMediumDefaultUnderlineOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textMediumDefaultUnderlineOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textMediumDefaultUnderlineOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textMediumDefaultUnderlineOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textMediumDefaultUnderlineOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textMediumDefaultUnderlineOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textMediumDefaultUnderlineOverrides?.overflow ?? allOverrides?.overflow,
    );
    textMediumStrong = TextStyle(
      inherit: textMediumStrongOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textMediumStrongOverrides?.color ?? allOverrides?.color,
      backgroundColor: textMediumStrongOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textMediumStrongOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textMediumStrongOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textMediumStrongOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textMediumStrongOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textMediumStrongOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textMediumStrongOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textMediumStrongOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textMediumStrongOverrides?.height ?? allOverrides?.height,
      decoration: textMediumStrongOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textMediumStrongOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textMediumStrongOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textMediumStrongOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textMediumStrongOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textMediumStrongOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textMediumStrongOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textMediumStrongOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textMediumStrongOverrides?.overflow ?? allOverrides?.overflow,
    );
    textMediumStrongUppercase = TextStyle(
      inherit: textMediumStrongUppercaseOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textMediumStrongUppercaseOverrides?.color ?? allOverrides?.color,
      backgroundColor: textMediumStrongUppercaseOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textMediumStrongUppercaseOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textMediumStrongUppercaseOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textMediumStrongUppercaseOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textMediumStrongUppercaseOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textMediumStrongUppercaseOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textMediumStrongUppercaseOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textMediumStrongUppercaseOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textMediumStrongUppercaseOverrides?.height ?? allOverrides?.height,
      decoration: textMediumStrongUppercaseOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textMediumStrongUppercaseOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textMediumStrongUppercaseOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textMediumStrongUppercaseOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textMediumStrongUppercaseOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textMediumStrongUppercaseOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textMediumStrongUppercaseOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textMediumStrongUppercaseOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textMediumStrongUppercaseOverrides?.overflow ?? allOverrides?.overflow,
    );
    textMediumStrongUnderline = TextStyle(
      inherit: textMediumStrongUnderlineOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textMediumStrongUnderlineOverrides?.color ?? allOverrides?.color,
      backgroundColor: textMediumStrongUnderlineOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textMediumStrongUnderlineOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textMediumStrongUnderlineOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textMediumStrongUnderlineOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textMediumStrongUnderlineOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textMediumStrongUnderlineOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textMediumStrongUnderlineOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textMediumStrongUnderlineOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textMediumStrongUnderlineOverrides?.height ?? allOverrides?.height,
      decoration: textMediumStrongUnderlineOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textMediumStrongUnderlineOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textMediumStrongUnderlineOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textMediumStrongUnderlineOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textMediumStrongUnderlineOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textMediumStrongUnderlineOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textMediumStrongUnderlineOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textMediumStrongUnderlineOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textMediumStrongUnderlineOverrides?.overflow ?? allOverrides?.overflow,
    );
    textSmallDefault = TextStyle(
      inherit: textSmallDefaultOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textSmallDefaultOverrides?.color ?? allOverrides?.color,
      backgroundColor: textSmallDefaultOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textSmallDefaultOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textSmallDefaultOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textSmallDefaultOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textSmallDefaultOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textSmallDefaultOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textSmallDefaultOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textSmallDefaultOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textSmallDefaultOverrides?.height ?? allOverrides?.height,
      decoration: textSmallDefaultOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textSmallDefaultOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textSmallDefaultOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textSmallDefaultOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textSmallDefaultOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textSmallDefaultOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textSmallDefaultOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textSmallDefaultOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textSmallDefaultOverrides?.overflow ?? allOverrides?.overflow,
    );
    textSmallDefaultUppercase = TextStyle(
      inherit: textSmallDefaultUppercaseOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textSmallDefaultUppercaseOverrides?.color ?? allOverrides?.color,
      backgroundColor: textSmallDefaultUppercaseOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textSmallDefaultUppercaseOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textSmallDefaultUppercaseOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textSmallDefaultUppercaseOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textSmallDefaultUppercaseOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textSmallDefaultUppercaseOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textSmallDefaultUppercaseOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textSmallDefaultUppercaseOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textSmallDefaultUppercaseOverrides?.height ?? allOverrides?.height,
      decoration: textSmallDefaultUppercaseOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textSmallDefaultUppercaseOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textSmallDefaultUppercaseOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textSmallDefaultUppercaseOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textSmallDefaultUppercaseOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textSmallDefaultUppercaseOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textSmallDefaultUppercaseOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textSmallDefaultUppercaseOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textSmallDefaultUppercaseOverrides?.overflow ?? allOverrides?.overflow,
    );
    textSmallDefaultUnderline = TextStyle(
      inherit: textSmallDefaultUnderlineOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textSmallDefaultUnderlineOverrides?.color ?? allOverrides?.color,
      backgroundColor: textSmallDefaultUnderlineOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textSmallDefaultUnderlineOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textSmallDefaultUnderlineOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textSmallDefaultUnderlineOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textSmallDefaultUnderlineOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textSmallDefaultUnderlineOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textSmallDefaultUnderlineOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textSmallDefaultUnderlineOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textSmallDefaultUnderlineOverrides?.height ?? allOverrides?.height,
      decoration: textSmallDefaultUnderlineOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textSmallDefaultUnderlineOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textSmallDefaultUnderlineOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textSmallDefaultUnderlineOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textSmallDefaultUnderlineOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textSmallDefaultUnderlineOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textSmallDefaultUnderlineOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textSmallDefaultUnderlineOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textSmallDefaultUnderlineOverrides?.overflow ?? allOverrides?.overflow,
    );
    textSmallStrong = TextStyle(
      inherit: textSmallStrongOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textSmallStrongOverrides?.color ?? allOverrides?.color,
      backgroundColor: textSmallStrongOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textSmallStrongOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textSmallStrongOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textSmallStrongOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textSmallStrongOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textSmallStrongOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textSmallStrongOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textSmallStrongOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textSmallStrongOverrides?.height ?? allOverrides?.height,
      decoration: textSmallStrongOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textSmallStrongOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textSmallStrongOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textSmallStrongOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textSmallStrongOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textSmallStrongOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textSmallStrongOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textSmallStrongOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textSmallStrongOverrides?.overflow ?? allOverrides?.overflow,
    );
    textSmallStrongUppercase = TextStyle(
      inherit: textSmallStrongUppercaseOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textSmallStrongUppercaseOverrides?.color ?? allOverrides?.color,
      backgroundColor: textSmallStrongUppercaseOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textSmallStrongUppercaseOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textSmallStrongUppercaseOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textSmallStrongUppercaseOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textSmallStrongUppercaseOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textSmallStrongUppercaseOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textSmallStrongUppercaseOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textSmallStrongUppercaseOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textSmallStrongUppercaseOverrides?.height ?? allOverrides?.height,
      decoration: textSmallStrongUppercaseOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textSmallStrongUppercaseOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textSmallStrongUppercaseOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textSmallStrongUppercaseOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textSmallStrongUppercaseOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textSmallStrongUppercaseOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textSmallStrongUppercaseOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textSmallStrongUppercaseOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textSmallStrongUppercaseOverrides?.overflow ?? allOverrides?.overflow,
    );
    textSmallStrongUnderline = TextStyle(
      inherit: textSmallStrongUnderlineOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textSmallStrongUnderlineOverrides?.color ?? allOverrides?.color,
      backgroundColor: textSmallStrongUnderlineOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textSmallStrongUnderlineOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textSmallStrongUnderlineOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textSmallStrongUnderlineOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textSmallStrongUnderlineOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textSmallStrongUnderlineOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textSmallStrongUnderlineOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textSmallStrongUnderlineOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textSmallStrongUnderlineOverrides?.height ?? allOverrides?.height,
      decoration: textSmallStrongUnderlineOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textSmallStrongUnderlineOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textSmallStrongUnderlineOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textSmallStrongUnderlineOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textSmallStrongUnderlineOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textSmallStrongUnderlineOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textSmallStrongUnderlineOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textSmallStrongUnderlineOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textSmallStrongUnderlineOverrides?.overflow ?? allOverrides?.overflow,
    );
    textXsmallDefault = TextStyle(
      inherit: textXsmallDefaultOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textXsmallDefaultOverrides?.color ?? allOverrides?.color,
      backgroundColor: textXsmallDefaultOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textXsmallDefaultOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textXsmallDefaultOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textXsmallDefaultOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textXsmallDefaultOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textXsmallDefaultOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textXsmallDefaultOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textXsmallDefaultOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textXsmallDefaultOverrides?.height ?? allOverrides?.height,
      decoration: textXsmallDefaultOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textXsmallDefaultOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textXsmallDefaultOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textXsmallDefaultOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textXsmallDefaultOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textXsmallDefaultOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textXsmallDefaultOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textXsmallDefaultOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textXsmallDefaultOverrides?.overflow ?? allOverrides?.overflow,
    );
    textXsmallDefaultUppercase = TextStyle(
      inherit: textXsmallDefaultUppercaseOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textXsmallDefaultUppercaseOverrides?.color ?? allOverrides?.color,
      backgroundColor: textXsmallDefaultUppercaseOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textXsmallDefaultUppercaseOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textXsmallDefaultUppercaseOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textXsmallDefaultUppercaseOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textXsmallDefaultUppercaseOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textXsmallDefaultUppercaseOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textXsmallDefaultUppercaseOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textXsmallDefaultUppercaseOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textXsmallDefaultUppercaseOverrides?.height ?? allOverrides?.height,
      decoration: textXsmallDefaultUppercaseOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textXsmallDefaultUppercaseOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textXsmallDefaultUppercaseOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textXsmallDefaultUppercaseOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textXsmallDefaultUppercaseOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textXsmallDefaultUppercaseOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textXsmallDefaultUppercaseOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textXsmallDefaultUppercaseOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textXsmallDefaultUppercaseOverrides?.overflow ?? allOverrides?.overflow,
    );
    textXsmallDefaultUnderline = TextStyle(
      inherit: textXsmallDefaultUnderlineOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textXsmallDefaultUnderlineOverrides?.color ?? allOverrides?.color,
      backgroundColor: textXsmallDefaultUnderlineOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textXsmallDefaultUnderlineOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textXsmallDefaultUnderlineOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textXsmallDefaultUnderlineOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textXsmallDefaultUnderlineOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textXsmallDefaultUnderlineOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textXsmallDefaultUnderlineOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textXsmallDefaultUnderlineOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textXsmallDefaultUnderlineOverrides?.height ?? allOverrides?.height,
      decoration: textXsmallDefaultUnderlineOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textXsmallDefaultUnderlineOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textXsmallDefaultUnderlineOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textXsmallDefaultUnderlineOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textXsmallDefaultUnderlineOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textXsmallDefaultUnderlineOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textXsmallDefaultUnderlineOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textXsmallDefaultUnderlineOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textXsmallDefaultUnderlineOverrides?.overflow ?? allOverrides?.overflow,
    );
    textXsmallStrong = TextStyle(
      inherit: textXsmallStrongOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textXsmallStrongOverrides?.color ?? allOverrides?.color,
      backgroundColor: textXsmallStrongOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textXsmallStrongOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textXsmallStrongOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textXsmallStrongOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textXsmallStrongOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textXsmallStrongOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textXsmallStrongOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textXsmallStrongOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textXsmallStrongOverrides?.height ?? allOverrides?.height,
      decoration: textXsmallStrongOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textXsmallStrongOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textXsmallStrongOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textXsmallStrongOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textXsmallStrongOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textXsmallStrongOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textXsmallStrongOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textXsmallStrongOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textXsmallStrongOverrides?.overflow ?? allOverrides?.overflow,
    );
    textXsmallStrongUppercase = TextStyle(
      inherit: textXsmallStrongUppercaseOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textXsmallStrongUppercaseOverrides?.color ?? allOverrides?.color,
      backgroundColor: textXsmallStrongUppercaseOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textXsmallStrongUppercaseOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textXsmallStrongUppercaseOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textXsmallStrongUppercaseOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textXsmallStrongUppercaseOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textXsmallStrongUppercaseOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textXsmallStrongUppercaseOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textXsmallStrongUppercaseOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textXsmallStrongUppercaseOverrides?.height ?? allOverrides?.height,
      decoration: textXsmallStrongUppercaseOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textXsmallStrongUppercaseOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textXsmallStrongUppercaseOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textXsmallStrongUppercaseOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textXsmallStrongUppercaseOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textXsmallStrongUppercaseOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textXsmallStrongUppercaseOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textXsmallStrongUppercaseOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textXsmallStrongUppercaseOverrides?.overflow ?? allOverrides?.overflow,
    );
    textXsmallStrongUnderline = TextStyle(
      inherit: textXsmallStrongUnderlineOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textXsmallStrongUnderlineOverrides?.color ?? allOverrides?.color,
      backgroundColor: textXsmallStrongUnderlineOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textXsmallStrongUnderlineOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textXsmallStrongUnderlineOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textXsmallStrongUnderlineOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textXsmallStrongUnderlineOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textXsmallStrongUnderlineOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textXsmallStrongUnderlineOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textXsmallStrongUnderlineOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textXsmallStrongUnderlineOverrides?.height ?? allOverrides?.height,
      decoration: textXsmallStrongUnderlineOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textXsmallStrongUnderlineOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textXsmallStrongUnderlineOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textXsmallStrongUnderlineOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textXsmallStrongUnderlineOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textXsmallStrongUnderlineOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textXsmallStrongUnderlineOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textXsmallStrongUnderlineOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textXsmallStrongUnderlineOverrides?.overflow ?? allOverrides?.overflow,
    );
    textTinyDefault = TextStyle(
      inherit: textTinyDefaultOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textTinyDefaultOverrides?.color ?? allOverrides?.color,
      backgroundColor: textTinyDefaultOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textTinyDefaultOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textTinyDefaultOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textTinyDefaultOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textTinyDefaultOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textTinyDefaultOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textTinyDefaultOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textTinyDefaultOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textTinyDefaultOverrides?.height ?? allOverrides?.height,
      decoration: textTinyDefaultOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textTinyDefaultOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textTinyDefaultOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textTinyDefaultOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textTinyDefaultOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textTinyDefaultOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textTinyDefaultOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textTinyDefaultOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textTinyDefaultOverrides?.overflow ?? allOverrides?.overflow,
    );
    textTinyDefaultUppercase = TextStyle(
      inherit: textTinyDefaultUppercaseOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textTinyDefaultUppercaseOverrides?.color ?? allOverrides?.color,
      backgroundColor: textTinyDefaultUppercaseOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textTinyDefaultUppercaseOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textTinyDefaultUppercaseOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textTinyDefaultUppercaseOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textTinyDefaultUppercaseOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textTinyDefaultUppercaseOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textTinyDefaultUppercaseOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textTinyDefaultUppercaseOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textTinyDefaultUppercaseOverrides?.height ?? allOverrides?.height,
      decoration: textTinyDefaultUppercaseOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textTinyDefaultUppercaseOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textTinyDefaultUppercaseOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textTinyDefaultUppercaseOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textTinyDefaultUppercaseOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textTinyDefaultUppercaseOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textTinyDefaultUppercaseOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textTinyDefaultUppercaseOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textTinyDefaultUppercaseOverrides?.overflow ?? allOverrides?.overflow,
    );
    textTinyDefaultUnderline = TextStyle(
      inherit: textTinyDefaultUnderlineOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textTinyDefaultUnderlineOverrides?.color ?? allOverrides?.color,
      backgroundColor: textTinyDefaultUnderlineOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textTinyDefaultUnderlineOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textTinyDefaultUnderlineOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textTinyDefaultUnderlineOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textTinyDefaultUnderlineOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textTinyDefaultUnderlineOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textTinyDefaultUnderlineOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textTinyDefaultUnderlineOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textTinyDefaultUnderlineOverrides?.height ?? allOverrides?.height,
      decoration: textTinyDefaultUnderlineOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textTinyDefaultUnderlineOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textTinyDefaultUnderlineOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textTinyDefaultUnderlineOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textTinyDefaultUnderlineOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textTinyDefaultUnderlineOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textTinyDefaultUnderlineOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textTinyDefaultUnderlineOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textTinyDefaultUnderlineOverrides?.overflow ?? allOverrides?.overflow,
    );
    textTinyStrong = TextStyle(
      inherit: textTinyStrongOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textTinyStrongOverrides?.color ?? allOverrides?.color,
      backgroundColor: textTinyStrongOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textTinyStrongOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textTinyStrongOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textTinyStrongOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textTinyStrongOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textTinyStrongOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textTinyStrongOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textTinyStrongOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textTinyStrongOverrides?.height ?? allOverrides?.height,
      decoration: textTinyStrongOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textTinyStrongOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textTinyStrongOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textTinyStrongOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textTinyStrongOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textTinyStrongOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textTinyStrongOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textTinyStrongOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textTinyStrongOverrides?.overflow ?? allOverrides?.overflow,
    );
    textTinyStrongUppercase = TextStyle(
      inherit: textTinyStrongUppercaseOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textTinyStrongUppercaseOverrides?.color ?? allOverrides?.color,
      backgroundColor: textTinyStrongUppercaseOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textTinyStrongUppercaseOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textTinyStrongUppercaseOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textTinyStrongUppercaseOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textTinyStrongUppercaseOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textTinyStrongUppercaseOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textTinyStrongUppercaseOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textTinyStrongUppercaseOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textTinyStrongUppercaseOverrides?.height ?? allOverrides?.height,
      decoration: textTinyStrongUppercaseOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textTinyStrongUppercaseOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textTinyStrongUppercaseOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textTinyStrongUppercaseOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textTinyStrongUppercaseOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textTinyStrongUppercaseOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textTinyStrongUppercaseOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textTinyStrongUppercaseOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textTinyStrongUppercaseOverrides?.overflow ?? allOverrides?.overflow,
    );
    textTinyStrongUnderline = TextStyle(
      inherit: textTinyStrongUnderlineOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textTinyStrongUnderlineOverrides?.color ?? allOverrides?.color,
      backgroundColor: textTinyStrongUnderlineOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textTinyStrongUnderlineOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "{font-fam.text}",
      fontSize: textTinyStrongUnderlineOverrides?.fontSize ?? allOverrides?.fontSize,
      fontWeight: textTinyStrongUnderlineOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textTinyStrongUnderlineOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textTinyStrongUnderlineOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textTinyStrongUnderlineOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textTinyStrongUnderlineOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textTinyStrongUnderlineOverrides?.height ?? allOverrides?.height,
      decoration: textTinyStrongUnderlineOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textTinyStrongUnderlineOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textTinyStrongUnderlineOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textTinyStrongUnderlineOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textTinyStrongUnderlineOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textTinyStrongUnderlineOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textTinyStrongUnderlineOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textTinyStrongUnderlineOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textTinyStrongUnderlineOverrides?.overflow ?? allOverrides?.overflow,
    );
  }
}
