import 'package:flutter/material.dart';

class ExampleTextTheme {
  final TextStyle titleMicro;
  final TextStyle titleTiny;
  final TextStyle titleExtraSmall;
  final TextStyle titleSmall;
  final TextStyle titleMedium;
  final TextStyle titleLarge;
  final TextStyle titleExtraLarge;
  final TextStyle titleDisplaySmall;
  final TextStyle titleDisplayMedium;
  final TextStyle titleDisplayLarge;
  final TextStyle textRegularMicro;
  final TextStyle textRegularTiny;
  final TextStyle textRegularExtraSmall;
  final TextStyle textRegularSmall;
  final TextStyle textRegularMedium;
  final TextStyle textRegularLarge;
  final TextStyle textBoldMicro;
  final TextStyle textBoldTiny;
  final TextStyle textBoldExtraSmall;
  final TextStyle textBoldSmall;
  final TextStyle textBoldMedium;
  final TextStyle textBoldLarge;

  const ExampleTextTheme()
      : titleMicro = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Playfair Display", fontSize: 14.0, fontWeight: FontWeight.bold, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        titleTiny = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Playfair Display", fontSize: 16.0, fontWeight: FontWeight.bold, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        titleExtraSmall = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Playfair Display", fontSize: 18.0, fontWeight: FontWeight.bold, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        titleSmall = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Playfair Display", fontSize: 20.0, fontWeight: FontWeight.bold, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        titleMedium = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Playfair Display", fontSize: 22.0, fontWeight: FontWeight.bold, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        titleLarge = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Playfair Display", fontSize: 24.0, fontWeight: FontWeight.bold, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        titleExtraLarge = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Playfair Display", fontSize: 28.0, fontWeight: FontWeight.bold, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        titleDisplaySmall = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Playfair Display", fontSize: 32.0, fontWeight: FontWeight.bold, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        titleDisplayMedium = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Playfair Display", fontSize: 36.0, fontWeight: FontWeight.bold, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        titleDisplayLarge = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Playfair Display", fontSize: 40.0, fontWeight: FontWeight.bold, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        textRegularMicro = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Heebo", fontSize: null, fontWeight: FontWeight.w400, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        textRegularTiny = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Heebo", fontSize: null, fontWeight: FontWeight.w400, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        textRegularExtraSmall = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Heebo", fontSize: null, fontWeight: FontWeight.w400, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        textRegularSmall = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Heebo", fontSize: null, fontWeight: FontWeight.w400, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        textRegularMedium = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Heebo", fontSize: null, fontWeight: FontWeight.w400, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        textRegularLarge = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Heebo", fontSize: null, fontWeight: FontWeight.w400, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        textBoldMicro = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Heebo", fontSize: null, fontWeight: FontWeight.w500, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        textBoldTiny = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Heebo", fontSize: null, fontWeight: FontWeight.w500, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        textBoldExtraSmall = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Heebo", fontSize: null, fontWeight: FontWeight.w500, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        textBoldSmall = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Heebo", fontSize: null, fontWeight: FontWeight.w500, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        textBoldMedium = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Heebo", fontSize: null, fontWeight: FontWeight.w500, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null),
        textBoldLarge = const TextStyle(inherit: true, color: null, backgroundColor: null, fontFamily: "Heebo", fontSize: null, fontWeight: FontWeight.w500, fontStyle: null, letterSpacing: 0.0, wordSpacing: null, textBaseline: null, height: null, decoration: null, decorationColor: null, decorationStyle: null, decorationThickness: null, debugLabel: null, shadows: null, fontFeatures: null, fontVariations: null, overflow: null);
}
