import 'package:flutter/material.dart';

class ExampleTextTheme {
  late final TextStyle textTabbarLabel;
  late final TextStyle textStrongXSmall;
  late final TextStyle textStrongSmall;
  late final TextStyle textStrongMedium;
  late final TextStyle textDefaultXSmall;
  late final TextStyle textDefaultSmall;
  late final TextStyle textDefaultMedium;
  late final TextStyle textStrongUnderlineXSmall;
  late final TextStyle textStrongUnderlineSmall;
  late final TextStyle textStrongUnderlineMedium;
  late final TextStyle titleSmall;
  late final TextStyle titleXSmall;
  late final TextStyle titleMedium;

  ExampleTextTheme({
    TextStyle? allOverrides,
    TextStyle? textTabbarLabelOverrides,
    TextStyle? textStrongXSmallOverrides,
    TextStyle? textStrongSmallOverrides,
    TextStyle? textStrongMediumOverrides,
    TextStyle? textDefaultXSmallOverrides,
    TextStyle? textDefaultSmallOverrides,
    TextStyle? textDefaultMediumOverrides,
    TextStyle? textStrongUnderlineXSmallOverrides,
    TextStyle? textStrongUnderlineSmallOverrides,
    TextStyle? textStrongUnderlineMediumOverrides,
    TextStyle? titleSmallOverrides,
    TextStyle? titleXSmallOverrides,
    TextStyle? titleMediumOverrides,
  }) {
    textTabbarLabel = TextStyle(
      inherit: textTabbarLabelOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textTabbarLabelOverrides?.color ?? allOverrides?.color,
      backgroundColor: textTabbarLabelOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textTabbarLabelOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: textTabbarLabelOverrides?.fontSize ?? allOverrides?.fontSize ?? 10.0,
      fontWeight: textTabbarLabelOverrides?.fontWeight ?? allOverrides?.fontWeight ?? FontWeight.w500,
      fontStyle: textTabbarLabelOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textTabbarLabelOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textTabbarLabelOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textTabbarLabelOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textTabbarLabelOverrides?.height ?? allOverrides?.height,
      decoration: textTabbarLabelOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textTabbarLabelOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textTabbarLabelOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textTabbarLabelOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textTabbarLabelOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textTabbarLabelOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textTabbarLabelOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textTabbarLabelOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textTabbarLabelOverrides?.overflow ?? allOverrides?.overflow,
    );
    textStrongXSmall = TextStyle(
      inherit: textStrongXSmallOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textStrongXSmallOverrides?.color ?? allOverrides?.color,
      backgroundColor: textStrongXSmallOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textStrongXSmallOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: textStrongXSmallOverrides?.fontSize ?? allOverrides?.fontSize ?? 11.0,
      fontWeight: textStrongXSmallOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textStrongXSmallOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textStrongXSmallOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textStrongXSmallOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textStrongXSmallOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textStrongXSmallOverrides?.height ?? allOverrides?.height,
      decoration: textStrongXSmallOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textStrongXSmallOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textStrongXSmallOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textStrongXSmallOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textStrongXSmallOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textStrongXSmallOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textStrongXSmallOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textStrongXSmallOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textStrongXSmallOverrides?.overflow ?? allOverrides?.overflow,
    );
    textStrongSmall = TextStyle(
      inherit: textStrongSmallOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textStrongSmallOverrides?.color ?? allOverrides?.color,
      backgroundColor: textStrongSmallOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textStrongSmallOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: textStrongSmallOverrides?.fontSize ?? allOverrides?.fontSize ?? 13.0,
      fontWeight: textStrongSmallOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textStrongSmallOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textStrongSmallOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textStrongSmallOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textStrongSmallOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textStrongSmallOverrides?.height ?? allOverrides?.height ?? 1.3846153846153846,
      decoration: textStrongSmallOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textStrongSmallOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textStrongSmallOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textStrongSmallOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textStrongSmallOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textStrongSmallOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textStrongSmallOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textStrongSmallOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textStrongSmallOverrides?.overflow ?? allOverrides?.overflow,
    );
    textStrongMedium = TextStyle(
      inherit: textStrongMediumOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textStrongMediumOverrides?.color ?? allOverrides?.color,
      backgroundColor: textStrongMediumOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textStrongMediumOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: textStrongMediumOverrides?.fontSize ?? allOverrides?.fontSize ?? 15.0,
      fontWeight: textStrongMediumOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textStrongMediumOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textStrongMediumOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textStrongMediumOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textStrongMediumOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textStrongMediumOverrides?.height ?? allOverrides?.height,
      decoration: textStrongMediumOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textStrongMediumOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textStrongMediumOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textStrongMediumOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textStrongMediumOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textStrongMediumOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textStrongMediumOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textStrongMediumOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textStrongMediumOverrides?.overflow ?? allOverrides?.overflow,
    );
    textDefaultXSmall = TextStyle(
      inherit: textDefaultXSmallOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textDefaultXSmallOverrides?.color ?? allOverrides?.color,
      backgroundColor: textDefaultXSmallOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textDefaultXSmallOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: textDefaultXSmallOverrides?.fontSize ?? allOverrides?.fontSize ?? 11.0,
      fontWeight: textDefaultXSmallOverrides?.fontWeight ?? allOverrides?.fontWeight ?? FontWeight.w400,
      fontStyle: textDefaultXSmallOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textDefaultXSmallOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textDefaultXSmallOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textDefaultXSmallOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textDefaultXSmallOverrides?.height ?? allOverrides?.height,
      decoration: textDefaultXSmallOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textDefaultXSmallOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textDefaultXSmallOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textDefaultXSmallOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textDefaultXSmallOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textDefaultXSmallOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textDefaultXSmallOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textDefaultXSmallOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textDefaultXSmallOverrides?.overflow ?? allOverrides?.overflow,
    );
    textDefaultSmall = TextStyle(
      inherit: textDefaultSmallOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textDefaultSmallOverrides?.color ?? allOverrides?.color,
      backgroundColor: textDefaultSmallOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textDefaultSmallOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: textDefaultSmallOverrides?.fontSize ?? allOverrides?.fontSize ?? 13.0,
      fontWeight: textDefaultSmallOverrides?.fontWeight ?? allOverrides?.fontWeight ?? FontWeight.w400,
      fontStyle: textDefaultSmallOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textDefaultSmallOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textDefaultSmallOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textDefaultSmallOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textDefaultSmallOverrides?.height ?? allOverrides?.height ?? 1.3846153846153846,
      decoration: textDefaultSmallOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textDefaultSmallOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textDefaultSmallOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textDefaultSmallOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textDefaultSmallOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textDefaultSmallOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textDefaultSmallOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textDefaultSmallOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textDefaultSmallOverrides?.overflow ?? allOverrides?.overflow,
    );
    textDefaultMedium = TextStyle(
      inherit: textDefaultMediumOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textDefaultMediumOverrides?.color ?? allOverrides?.color,
      backgroundColor: textDefaultMediumOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textDefaultMediumOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: textDefaultMediumOverrides?.fontSize ?? allOverrides?.fontSize ?? 15.0,
      fontWeight: textDefaultMediumOverrides?.fontWeight ?? allOverrides?.fontWeight ?? FontWeight.w400,
      fontStyle: textDefaultMediumOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textDefaultMediumOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textDefaultMediumOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textDefaultMediumOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textDefaultMediumOverrides?.height ?? allOverrides?.height ?? 1.3333333333333333,
      decoration: textDefaultMediumOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textDefaultMediumOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textDefaultMediumOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textDefaultMediumOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textDefaultMediumOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textDefaultMediumOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textDefaultMediumOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textDefaultMediumOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textDefaultMediumOverrides?.overflow ?? allOverrides?.overflow,
    );
    textStrongUnderlineXSmall = TextStyle(
      inherit: textStrongUnderlineXSmallOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textStrongUnderlineXSmallOverrides?.color ?? allOverrides?.color,
      backgroundColor: textStrongUnderlineXSmallOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textStrongUnderlineXSmallOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: textStrongUnderlineXSmallOverrides?.fontSize ?? allOverrides?.fontSize ?? 11.0,
      fontWeight: textStrongUnderlineXSmallOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textStrongUnderlineXSmallOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textStrongUnderlineXSmallOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textStrongUnderlineXSmallOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textStrongUnderlineXSmallOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textStrongUnderlineXSmallOverrides?.height ?? allOverrides?.height,
      decoration: textStrongUnderlineXSmallOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textStrongUnderlineXSmallOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textStrongUnderlineXSmallOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textStrongUnderlineXSmallOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textStrongUnderlineXSmallOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textStrongUnderlineXSmallOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textStrongUnderlineXSmallOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textStrongUnderlineXSmallOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textStrongUnderlineXSmallOverrides?.overflow ?? allOverrides?.overflow,
    );
    textStrongUnderlineSmall = TextStyle(
      inherit: textStrongUnderlineSmallOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textStrongUnderlineSmallOverrides?.color ?? allOverrides?.color,
      backgroundColor: textStrongUnderlineSmallOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textStrongUnderlineSmallOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: textStrongUnderlineSmallOverrides?.fontSize ?? allOverrides?.fontSize ?? 13.0,
      fontWeight: textStrongUnderlineSmallOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textStrongUnderlineSmallOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textStrongUnderlineSmallOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textStrongUnderlineSmallOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textStrongUnderlineSmallOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textStrongUnderlineSmallOverrides?.height ?? allOverrides?.height ?? 1.3846153846153846,
      decoration: textStrongUnderlineSmallOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textStrongUnderlineSmallOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textStrongUnderlineSmallOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textStrongUnderlineSmallOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textStrongUnderlineSmallOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textStrongUnderlineSmallOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textStrongUnderlineSmallOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textStrongUnderlineSmallOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textStrongUnderlineSmallOverrides?.overflow ?? allOverrides?.overflow,
    );
    textStrongUnderlineMedium = TextStyle(
      inherit: textStrongUnderlineMediumOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: textStrongUnderlineMediumOverrides?.color ?? allOverrides?.color,
      backgroundColor: textStrongUnderlineMediumOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: textStrongUnderlineMediumOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: textStrongUnderlineMediumOverrides?.fontSize ?? allOverrides?.fontSize ?? 15.0,
      fontWeight: textStrongUnderlineMediumOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: textStrongUnderlineMediumOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: textStrongUnderlineMediumOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: textStrongUnderlineMediumOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: textStrongUnderlineMediumOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: textStrongUnderlineMediumOverrides?.height ?? allOverrides?.height,
      decoration: textStrongUnderlineMediumOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: textStrongUnderlineMediumOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: textStrongUnderlineMediumOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: textStrongUnderlineMediumOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: textStrongUnderlineMediumOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: textStrongUnderlineMediumOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: textStrongUnderlineMediumOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: textStrongUnderlineMediumOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: textStrongUnderlineMediumOverrides?.overflow ?? allOverrides?.overflow,
    );
    titleSmall = TextStyle(
      inherit: titleSmallOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: titleSmallOverrides?.color ?? allOverrides?.color,
      backgroundColor: titleSmallOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: titleSmallOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: titleSmallOverrides?.fontSize ?? allOverrides?.fontSize ?? 20.0,
      fontWeight: titleSmallOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: titleSmallOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: titleSmallOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: titleSmallOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: titleSmallOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: titleSmallOverrides?.height ?? allOverrides?.height,
      decoration: titleSmallOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: titleSmallOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: titleSmallOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: titleSmallOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: titleSmallOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: titleSmallOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: titleSmallOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: titleSmallOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: titleSmallOverrides?.overflow ?? allOverrides?.overflow,
    );
    titleXSmall = TextStyle(
      inherit: titleXSmallOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: titleXSmallOverrides?.color ?? allOverrides?.color,
      backgroundColor: titleXSmallOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: titleXSmallOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: titleXSmallOverrides?.fontSize ?? allOverrides?.fontSize ?? 18.0,
      fontWeight: titleXSmallOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: titleXSmallOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: titleXSmallOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: titleXSmallOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: titleXSmallOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: titleXSmallOverrides?.height ?? allOverrides?.height,
      decoration: titleXSmallOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: titleXSmallOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: titleXSmallOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: titleXSmallOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: titleXSmallOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: titleXSmallOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: titleXSmallOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: titleXSmallOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: titleXSmallOverrides?.overflow ?? allOverrides?.overflow,
    );
    titleMedium = TextStyle(
      inherit: titleMediumOverrides?.inherit ?? allOverrides?.inherit ?? true,
      color: titleMediumOverrides?.color ?? allOverrides?.color,
      backgroundColor: titleMediumOverrides?.backgroundColor ?? allOverrides?.backgroundColor,
      fontFamily: titleMediumOverrides?.fontFamily ?? allOverrides?.fontFamily ?? "SF Pro Text",
      fontSize: titleMediumOverrides?.fontSize ?? allOverrides?.fontSize ?? 24.0,
      fontWeight: titleMediumOverrides?.fontWeight ?? allOverrides?.fontWeight,
      fontStyle: titleMediumOverrides?.fontStyle ?? allOverrides?.fontStyle,
      letterSpacing: titleMediumOverrides?.letterSpacing ?? allOverrides?.letterSpacing,
      wordSpacing: titleMediumOverrides?.wordSpacing ?? allOverrides?.wordSpacing,
      textBaseline: titleMediumOverrides?.textBaseline ?? allOverrides?.textBaseline,
      height: titleMediumOverrides?.height ?? allOverrides?.height,
      decoration: titleMediumOverrides?.decoration ?? allOverrides?.decoration,
      decorationColor: titleMediumOverrides?.decorationColor ?? allOverrides?.decorationColor,
      decorationStyle: titleMediumOverrides?.decorationStyle ?? allOverrides?.decorationStyle,
      decorationThickness: titleMediumOverrides?.decorationThickness ?? allOverrides?.decorationThickness,
      debugLabel: titleMediumOverrides?.debugLabel ?? allOverrides?.debugLabel,
      shadows: titleMediumOverrides?.shadows ?? allOverrides?.shadows,
      fontFeatures: titleMediumOverrides?.fontFeatures ?? allOverrides?.fontFeatures,
      fontVariations: titleMediumOverrides?.fontVariations ?? allOverrides?.fontVariations,
      overflow: titleMediumOverrides?.overflow ?? allOverrides?.overflow,
    );
  }
}
